version: '3'

services:
  db:
    image: postgres:12-alpine
    env_file: ./env.docker
    volumes:
      - db:/var/lib/postgresql/data

  app:
    container_name: app-api
    build:
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    command: "pipenv run uvicorn api.main:app --host 0.0.0.0 --port 8181 --reload"
    volumes:
      - ./:/app
    env_file: ./env.docker
    depends_on:
      - db

volumes:
  db:
