name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: superdbpassword
          POSTGRES_DB: app_development
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pipenv
        run: pip install pipenv

      - name: Setup Database
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run tests
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: superdbpassword
          POSTGRES_DB: app_development
          POSTGRES_PORT: 5432
          POSTGRES_SERVER: 127.0.0.1
          API_AUTH_TOKEN: fake-token
          LOG_LEVEL: DEBUG

        run: |
          pip install sqlalchemy
          pip install psycopg2
          python tests_setup_db.py
          pipenv install --dev
          pipenv run pytest
